backend:
  name: github
  repo: codema-dev/codema-dev.github.io
  branch: gh-pages # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }